### ISSUE TITLE
Mission Stubs

### ISSUE THREAD

**Issue by kaifox** [molr/molr#26]
I think we could have something like:

```
MissionStub<Double, Boolean> LAND_THE_FALCON = MissionStubs.stub("Land Falcon").withParam(Double.class).withReturnValue(Boolean.class, "returnValue");

// simplified call of a mission could then be

// give it a good name ;-)
MoleConvenienceDecorator dec = MoleConvenienceDecorator.from(mole);


Boolean success = dec.call(LAND_THE_FALCON).param(0.2).block();
Boolean success = dec.call(LAND_THE_FALCON).param(0.2).block();
Mono<Boolean> success = dec.call(LAND_THE_FALCON).param(0.2).async();

// without stubs it would look e.g. like:

Boolean success = dec.call("Land Falcon",  param1(0.2), return(Boolean.class));

```

**Comment by kaifox** [comment]
Just discovered: There is a starting point for this:
https://github.com/molr/molr/tree/master/molr-mole-core/src/main/java/io/molr/mole/core/support

**Comment by kaifox** [comment]
Thinking a bit further on this, and looking at the started classes, I think the general road would be rather similar to what we would do without the stubs ...

As started in the actual convenience class, there should be different variants where one can decide how to use the calling mechanism. The variants might include:

* Start a mission, do some more code, and then await the end of the mission.
* awaiting the mission shall be possible to do with or without a timeout
* when awaiting the end of the mission, one should be able to decide what to get at the end: Simply the return value, the full mission state or just the result (successful, failed...)

Probably it is a good idea to split this story in 2.... 
1. Work on the class which is now called AgencyConvenienceSupport (should probably be renamed into something like `ConvenienceMissionController`
2. Implement the actual stubbing mechanism, which is simply yet more sugar on top (typed calls). However, all the await mechanics etc would just be delegates to the ConvenienceMissionController.

Does this sound reasonable? I will try to make a separate issue for this controller and put more information there....

**Comment by kaifox** [comment]
In the end, it might be that the entry points for stubs just would return the same `OngoingMissionRun` as described in #33, and thus provide the same features. The only difference here would be that we have type safety for parameters ;-)

**Comment by HimanshuSahu31** [comment]
We would have to pass executable as well to instantiate SIngleNodeMission using these stubs. An example of how that will look would be helpful. 
What would be the default behavior if either of param type, return type or executable is not specified? Throw an exception?

**Comment by kaifox** [comment]
No, that I think is exactly what should not happen ... the 'address' of a mission (currently simply the name) should be sufficient....

I think you are right ... we might have to rethink a bit after the experience from the MissionControlSupport ... I will try to think a bit more and come up with some better (and probably rethought) examples tomorrow... (Sorry, do not manage today).

Kajetan

**Comment by kaifox** [comment]
There is a proposal in a new pull request: #36 
(So the initial text of the issue is more or less deprecated)
