### ISSUE TITLE
The mole should generate the instance handle

### ISSUE THREAD

**Issue by michi42** [molr/molr#4]
Currently, the instance handle for a mission is generated by the agency. This leads to issues if the same ID has already been used on a particular mole, e.g. if the agency was restarted or the mole serves multiple agencies (as the REST API allows - and the name "mole" indicates ;-)).

I think it would be more logical to generate the instance handle on the mole, and return it when instantiate() is called. For communication with the mole, it only has to be unique per mole, not globally on the agency.

**Comment by kaifox** [comment]
Mhmm indeed... there you hit some point (in particular the sentence 'if it serves different agencies' sounds convincing ... indeed this is not prohibited ;-)

...what is a bit unclear to me how the agency would handle this... Currently, it relies on unique ids per agency ... it could somehow prefix with a mole-id? Any better ideas....?

On the other hand: This was more or less the only difference in the method signatures between agencies and moles .... (Except the reactive return types ... which were more a matter of taste than enforcing ...)

This to say:
Probably, we are converging into a situation where the interface of a mole and an agency are the same? So the agency is just kind of a MultipleDelegatingMole ?
... could be.... Would be convenient ... then the GUI can act on either one ...

**Comment by kaifox** [comment]
This is fixed, I think, as anyway there is no separate Agency anymore. Everything is a mole ;-)
