### ISSUE TITLE
A mole could provide a set of options for a parameter

### ISSUE THREAD

**Issue by kaifox** [molr/molr#46]
Consider, having e.g. an input parameter for a sequence that has a finite number of possible options. This one could be delivered to clients within the parameter description. Then the client could e.g. display them in a combobox (or listbox) for the user to select ....
Examples of this could be e.g. lists of devices.

One way to specify this could be e.g in the dsl for the RunnableLeafsMole:
```
Placeholder<String> landingLocation = Placeholder.aString("landingLocation");
mandatory(landingLocation).options("Atlantic", "Pacific", "Cape Canaveral");
```

The shortcoming, which will follow immediately is that it is not always the case that the options for a parameter stay constant. Therefore it might well be that such lists have to be retrieved at runtime ...

On path to think in this direction could be some kind of ParameterOptionProvider, which can be plugged in through spring ... something like:

```
interface ParameterOptionProvider {
  /* default implementation returns empy lists */
  <T> List<T> optionsFor(Mission mission, Parameter<T> parameter);
}
```

This then could either be used internally in the mole or exposed to clients through a separate service ... To be thought what is better ;-)

**Comment by michi42** [comment]
I agree this would be nice. But more conceptually, what about seeing this as a custom enum-like type which could be used instead of one of the basic types like String/Int/Boolean/etc.? 

For example, on the protocol level, you would have ...
```json
{"parameters": [
  {"name":"oneParam", "type": "string", "required": true, "defaultValue": "test"},
  {"name":"secondParam", "type":"enum", "enumValues": ["A","B","C"], "required": true, "defaultValue": "A"},
]}```
I would then also map Java/python/... Enum to this, so on the code level you would have
```java
enum LandingLocation {
   ATLANTIC, PACIFIC, CAPE_CANAVERAL
}

Placeholder<LandingLocation> landingLocation = Placeholder.anEnum("landingLocation", LandingLocation.class);
```

In a first step, I would require them not to change during runtime. How would you otherwise specify the parameter values? I thought at the moment you set them when you launch a mission?

**Comment by kaifox** [comment]
Indeed the enum type is also a nice idea ... In my opinion it is a bit complementary I would say ...

Having a string (or any other type with options) could allow the options, but also a custom string (optionally ;-) Potentially, I would rather see the enum type as a particular implementation of 'string only with allowed set of values' .... And the enum only would be beneficial on the mission side ... At the client side, I would tend to avoid them ... otherwise we are back to coupling client and server ... and back to hell ;-)

Concerning the runtime part: Indeed, the first implementation would be not to change them at runtime.

However, there might be a bit of misunderstanding of what I meant by 'at runtime': I meant at runtime of the mole, not at runtime of the mission!. So for sure, those parameters must be given at instantiation time of the mission.

Still, the usecase to be allowed to provide allowed values at runtime of a mole is a valid (and not that complicated) one, I believe: 
As an example, let's consider e.g. a mission that requires a device name of a certain type. The list could be provided e.g. from a database ... or whatsoever ... Now, e.g. when starting the mission one e.g. discovers that a device is missing .... Just add it to the database, and at the next instantiation yoou can choose it ... That is what I meant by 'at runtime'.

**Comment by kaifox** [comment]
Cf enums: ok ... To remain uncoupled one could have an copy(!) of the enum at the client ... Could be a useful concept in combination with mission-stubs! ;-)

**Comment by kaifox** [comment]
How about having ...

```
{"parameters": [
  {"name":"oneParam", "type": "string", "required": true, "defaultValue": "test"},
  {"name":"secondParam", "type":"string", "exclusiveValues": ["A","B","C"], "required": true, "defaultValue": "A"},
 {"name":"thirdParam", "type":"integer", "valueOptions": [1,2,3], "required": true, "defaultValue": 1},
]}
```
* `secondParam` would allow only the values given
* `thirdParam` would offer the values given as options, but would also allow free input (e.g. in the gui like combobox with a text field)

On the mission side, 
```
Placeholder<LandingLocation> landingLocation = Placeholder.anEnum("landingLocation", LandingLocation.class);
```

would on the Api side transform into the `secondParam` type ... (exclusiveValues).

**Comment by michi42** [comment]
Sure, we should NOT require an enum object to be shared between client and mole to avoid coupling. In some cases it may not even be possible - thinking e.g. of a python mole accessed by a java client.
Basically a generic client should treat an "enum" exactly like your "secondParam" string parameter, offering a pre-defined set of values, e.g. in a ComboBox.
A dedicated client could either have its own copy of the enum, or in some cases even reuse the enum if it is a generic one (thinking e.g. of domain stuff from common libraries like Planes, Accelerators, Beams, ...).
I would just conceptually see this rather as an "enum" as in "a value type which can take a value from a predefined set". In many cases what matters in the first place are the items as entities themselves, not their string representation. Anyway, I guess in the end it's just a different naming ;-)

For the "valueOptions" in your last example, I'm not sure ... it sounds a bit like mixing up things, as then both the mole and the user (or dedicated client) somehow must know about what a "reasonable" value for that parameter is ...
I can imagine a few use cases where you want to offer a limited choice while keeping a "back door" for debugging/testing/... But perhaps in this case it would be better to provide an enum/exclusive list for regular operations and use a separate mission for testing purposes?

For the changing at runtime - indeed, I misunderstood.
Yes, to be able to refresh the list of available missions, their parameters etc, during the lifetime of the mole would be useful. However, I think in the end this is just a matter of our current implementation - the protocol should already allow this, right?

**Comment by kaifox** [comment]
Ok, I see .. I think we are mostly on the same line ... some naming to be clarified ...  ok, one can leave the value options out ... 

... concerning the last paragraph: Yes, I think the same: The protocol would allow it (as soon as we have implemented the options (or enum)) ... just the mole implementation would have to care ...
