### ISSUE TITLE
Support removal of active mission instances.

### ISSUE THREAD

**Issue by StefanGsi** [molr/molr#47]
We need an API to cleanup active mission instances.

Seems to be similar to #34

**Comment by kaifox** [comment]
I would consider this as duplicate of #34. Therefore, I will close the other one.

Just to note: We were thinking some time ago that probably it would make sense to implement some persistence mechanism first, before adressing this on. (See #25 )

**Comment by StefanGsi** [comment]
I have committed a first iteration/approach to remove mission instance from moles. Please check out the dispose-mission branches in molr and molr-gui-fx.
