### ISSUE TITLE
RunState - states can be pushed for leaves only but/and leafs are never paused

### ISSUE THREAD

**Issue by StefanGsi** [molr/molr#51]
RunStates for leafs are only set to RUNNING and FINISHED. Therefore states for leafs are UNDEFINED until LeafExecutor.execute is called. The state is updated to RUNNING then and to FINISHED after the runnable has been executed. This leads to inconsistent RunStates in case of breaks. For instance, if a block contains multiple children while some of them are finished and the execution of others is paused, then the parent state would be UNDEFINED but it should be PAUSED.

Somehow the PAUSED state for paused leafs/children of paused parent blocks must be pushed to the corresponding tracker.

**Comment by kaifox** [comment]
After discussion with @StefanGsi, we propose the following:

* rename the UNDEFINED state to NOT_STARTED
* have 2 different summarize methods (either in the enum or as external util), one for strands and one for nodes (this might not be fully necessary, but we might start with this as the rules might not be the same for both). As a first approach, the strandSummarize() would stay as the current one
* the nodeSummarize would always stay in "RUNNING" if the children have a mixed state (e.g. some FINISHED and some NOT_STARTED).

**Comment by andreacalia** [comment]
Hi guys, this looks good! :smile:

**Comment by StefanGsi** [comment]
Another issue regarding RunStates is that updated run states itself do not trigger corresponding updates on mission state. They are just fed into the mission states when other events trigger a re-calculation of the overall mission state. Therefore clients cannot rely on their missionStateSubscriptions in order to receive all run state updates on blocks. The RUNNING state of leafs may be missed completely.
