### ISSUE TITLE
Illeagal usage of (Emitter)Processor

### ISSUE THREAD

**Issue by StefanGsi** [molr/molr#91]
TreeMissionExecutor and OutputCollector use Reactor's FluxProceesor Interface which is illegal in their particular context since the onNext call is not thread safe. Subscribers can therefore not rely on deterministic behavior.

As a first workaround we may use a processor created FluxSink to emit items.

However processors will be removed in later reactor versions:
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/FluxProcessor.html

Therefore we should opt for no longer using them at all.

**Comment by kaifox** [comment]
Might be already closed?

**Comment by StefanGsi** [comment]
Issue has been fixed. However usage of processors is discouraged by reactor team and will be removed in future releases.

Therefor we will need to replace processors. New issue has been created.
https://github.com/molr/molr/issues/104
